# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: sudo apt-get install -y git calibre

      - run:
          name: Install gitbook
          command: |
            yarn install
            yarn run gitbook fetch
            yarn run gitbook install
          
      - run:
          name: Synchronize git branches
          command: |
            git config --global user.email $(git log -1 --pretty=format:'%ae')
            git config --global user.name $(git log -1 --pretty=format:'%an')
            git pull
            git rebase origin/gh-pages

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          
      - run:
          name: Build and Deploy Drillbook
          command: |
            yarn run gitbook build
            cp -R _book/* .
            LASTHASH=$(git rev-parse HEAD)
            git add .
            git commit -m "ci build of commit $LASTHASH"
            git checkout gh-pages
            git merge --ff-only master
            git push origin gh-pages
